In [36]:
import torch
import numpy as np  
tensor = torch.normal(0, 1, (2, 3))
tensor

tensor([[-0.0281,  0.9222,  0.1015],
        [-0.6450,  2.0672, -0.8082]])

In [37]:
tensor1 = tensor.to(torch.float32).reshape(-1)
tensor1

tensor([-0.0281,  0.9222,  0.1015, -0.6450,  2.0672, -0.8082])

In [35]:
for i in tensor1:
    print(str(i.item()))

-0.5686191320419312
-2.690969705581665
-1.6726453304290771
0.09197745472192764
0.8018040657043457
0.051378317177295685


In [39]:
tensor.size()

torch.Size([2, 3])

In [42]:
def transform_tensor(tensor):
    size = tensor.size()
    reshaped_tensor = tensor.view(-1)
    str_tensor = []
    for i in reshaped_tensor:
        str_tensor.append(str(i.item()))
    print(str_tensor)
    list_tensor = []
    for j in str_tensor:
        list_tensor.append(float(j))
    return torch.tensor(list_tensor).view(size)

In [43]:
transform_tensor(tensor)

['-0.02806933969259262', '0.9222459197044373', '0.10147816687822342', '-0.6450067162513733', '2.0672428607940674', '-0.8081963062286377']


tensor([[-0.0281,  0.9222,  0.1015],
        [-0.6450,  2.0672, -0.8082]])