In [16]:
import numpy as np
import phe
from phe import paillier
from tqdm import tqdm
vector = np.random.normal(0, 1, size=(3, 5, 7, 8))
print(len(vector.shape))
vector

4


array([[[[ 1.18121608e+00,  1.11828119e+00,  2.07128348e-01,
          -9.80550533e-01,  1.05711029e+00,  1.71452258e-01,
           4.28865577e-01, -3.03477057e-01],
         [ 1.20990102e-02, -5.01996910e-01, -8.93182606e-01,
           9.08195629e-01,  3.54113773e-01, -9.87374246e-02,
           2.13860121e-01,  3.05115666e-01],
         [-1.84687398e+00, -1.59180527e+00,  1.95126815e+00,
           3.53563405e-02, -1.87384449e+00, -1.48750376e+00,
           6.65657622e-01, -8.07887383e-01],
         [ 6.61211405e-01,  1.58162231e+00, -1.55084093e+00,
          -6.18977586e-01,  2.23196537e+00,  1.37563692e+00,
           8.16162231e-01,  6.34980315e-01],
         [-6.48146497e-01, -8.88556752e-01,  3.04125149e-01,
           1.05212756e+00, -1.02258400e+00, -5.90354739e-01,
          -1.39264607e+00,  4.40552336e-01],
         [-3.06840645e-01, -1.55844063e-01, -1.17101808e+00,
           4.90322641e-01, -7.05809952e-02,  1.48189185e-01,
          -5.32297573e-01,  6.11017302e-01]

In [8]:
vector.reshape(-1).reshape((3, 5, 7, 8))

array([[[[ 1.94937908e+00, -1.33015850e-01, -2.49752993e-01,
           5.02488626e-01, -5.55839105e-01,  1.19322207e+00,
          -1.42941735e+00, -1.17040147e+00],
         [-9.17975495e-01,  1.05929550e+00,  6.32918318e-01,
           2.32344831e-01,  8.49131855e-01,  2.66949165e-01,
           1.37055169e+00,  1.02914108e+00],
         [-1.89258329e+00,  1.43294526e+00, -2.02039399e-01,
           2.05255702e-01, -3.39033066e-02,  1.10941799e+00,
           1.20189441e+00, -9.61771128e-01],
         [-3.66191951e-01, -5.46004331e-01, -7.30063402e-01,
           1.45125603e+00, -1.01136386e+00,  6.06343324e-01,
          -8.91440288e-01, -1.13610934e+00],
         [-2.77165339e-01, -1.97874097e-01,  5.03619996e-01,
           8.31234502e-01, -3.00132572e-01,  1.03934459e-01,
          -7.28166317e-01,  5.45174059e-01],
         [ 6.25229558e-02,  8.03871526e-01, -5.05126026e-01,
          -1.50418707e+00, -1.73550619e+00,  1.48732823e+00,
           1.14133407e+00,  5.64910478e-01]

In [20]:
def encrypt_random_vector(vector):
    vector_shape = vector.shape
    vector_1d = vector.reshape(-1)
    keyring = paillier.PaillierPrivateKeyring()
    public_key = []
    encrypted_list = []
    for _ in range(len(vector_1d)):
        pub, priv = paillier.generate_paillier_keypair()
        public_key.append(pub)
        keyring.add(priv)
    for i in tqdm(range(len(vector_1d))):
        encrypted_list.append(public_key[i].encrypt(vector_1d[i], precision=1e-3))
    return encrypted_list, keyring, vector_shape

def decrypt_random_vector(encrypted):
    encrypted_list, keyring, vector_shape = encrypted[0], encrypted[1], encrypted[2]
    decrypted_list = []
    for i in tqdm(range(len(encrypted_list))):
        decrypted_list.append(keyring.decrypt(encrypted_list[i]))
    decrypted_vector = np.array(decrypted_list).reshape(vector_shape)
    return decrypted_vector

In [21]:
array = np.random.normal(0, 1, size=100)
encrypted = encrypt_random_vector(array)
decrypt_random_vector(encrypted)

100%|██████████| 100/100 [00:00<00:00, 144.80it/s]


array([-0.32836914,  0.8605957 , -0.99023438,  1.0300293 , -0.4699707 ,
       -0.55957031,  0.68945312, -0.36303711, -0.3515625 , -0.53271484,
        0.30786133, -0.90991211, -0.06054688, -0.05102539,  1.24658203,
        0.47192383, -0.9074707 ,  1.24707031,  1.29199219,  0.19897461,
        0.33984375,  0.66113281,  1.96850586, -2.59521484, -1.65771484,
       -0.5390625 , -0.24584961, -0.62060547, -1.67553711, -1.3515625 ,
        0.03149414,  1.17480469,  0.39648438,  0.04663086,  0.36132812,
       -0.78100586, -1.52832031, -1.49633789,  0.56005859, -0.20703125,
        1.43237305,  0.18945312,  0.98095703, -1.08666992, -0.64794922,
       -0.22460938,  0.76147461,  0.38037109,  1.32299805,  0.29589844,
        1.18212891,  0.6328125 , -0.32299805, -0.08105469, -1.55688477,
       -0.16748047,  0.09643555, -1.76489258,  0.5769043 ,  0.70678711,
       -2.33740234,  0.75415039, -0.10473633,  1.54370117,  0.18920898,
        1.79931641,  0.80664062, -0.20922852,  0.07714844, -0.31

In [22]:
array

array([-0.32848235,  0.86066029, -0.99025782,  1.0299792 , -0.46990965,
       -0.55963612,  0.68943124, -0.36311028, -0.35146799, -0.53262237,
        0.30792894, -0.90986202, -0.06065828, -0.05095306,  1.24647854,
        0.47190751, -0.90759082,  1.24716305,  1.29200552,  0.19885542,
        0.33980046,  0.66124739,  1.96862421, -2.59517039, -1.65783126,
       -0.53898013, -0.2458019 , -0.62057021, -1.67545314, -1.35147038,
        0.03144998,  1.17491149,  0.39646208,  0.0466591 ,  0.36120928,
       -0.78110197, -1.52832622, -1.49644356,  0.56006274, -0.20709408,
        1.43239382,  0.18957475,  0.98084681, -1.08662402, -0.64789806,
       -0.22468028,  0.76139156,  0.38043521,  1.32289134,  0.29595543,
        1.18210584,  0.63282102, -0.32310932, -0.0810379 , -1.55679619,
       -0.16745577,  0.09644023, -1.76481994,  0.57687885,  0.70675263,
       -2.33737765,  0.75404897, -0.10468416,  1.54365699,  0.18924614,
        1.79942378,  0.80662011, -0.20924095,  0.07708013, -0.31

# 尝试把区块链信息存储至数据库中
## 组合好TCN和nbeats，还有加密，应该加密哈希，通过哈希值和mining确定最长的链条并获得最终的信息，每个成员通过mining获得训练权